spring:
  application:
    name: backend

  profiles:
    active: local

springdoc:
  swagger-ui:
    path: /SWENG3-docs
    groups-order: asc
    operations-sorter: method
    disable-swagger-default-url: true
    display-operation-id: false
  api-docs:
    path: /SWENG3-api-docs

custom:
  env-name: "Base Environment"
  debug-mode: false
