spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false

  mail:
    host: smtp.naver.com
    port: 465
    username: ${NAVER_EMAIL}
    password: ${NAVER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

custom:
  env-name: "Production Mode"
  debug-mode: false
