spring:
  application:
    name: backend

springdoc:
  swagger-ui:
    path: /SWENG3-docs
    groups-order: asc
    operations-sorter: method
    disable-swagger-default-url: true
    display-operation-id: false
  api-docs:
    path: /SWENG3-api-docs
